- proj/xenguestlib/xenguestlib.csproj
- src/xenguestlib/Features.cs
Force add/remove exception in firewall for RDP
> CA-160190: Windows guests firewall exception force change

- src/xenguestlib/PVInstallation.cs
data/xd/present : 0 = not present, 1 = present
data/xd/product_installed : VDA ProductInstalled
Only set at start of day by the guest agent, not updated until
restarted (or resumed from suspend etc)
Signed-off-by: Ben Chalmers <Ben.Chalmers@citrix.com>
> [CP-11175] Report presence of XenDesktop VDA on Guest into xenstore

- src/xenguestagent/XenServiceInstaller.cs
> CA-176786: Add dependency of CryptSvc to guest agent

- proj/xenguestlib/xenguestlib.csproj
- src/xenguestagent/XenService.cs
- src/xenguestlib/AutoUpdate.cs
- src/xenguestlib/Clipboard.cs
- src/xenguestlib/Features.cs
- src/xenguestlib/Snapshot.cs
> CP-13694: Add automatic self-update to .net guest

- src/xenguestlib/AutoUpdate.cs
> CP-13694: Add update URL configuration from reg

- proj/xenguestlib/xenguestlib.csproj
- src/xenguestlib/AutoUpdate.cs
- src/xenguestlib/EventLogger.cs
> CP-14007: Add more event logs for guest agent automatic updates

- src/xenguestlib/Features.cs
> CA-174025: Guest Agent can read up to 1024 bytes in stdout/stderr

- src/xenguestlib/AutoUpdate.cs
> CA-184950: Add exception handling for auto upgrade MSI download

- proj/xenguestagent/xenguestagent.csproj
- src/xenguestagent/XenService.cs
- src/xenguestlib/NetInfo.cs
We have to iterate through the whole enum structure to find the
emulated network devices we want to remember about & copy
network data to.
Also add logging (so that we have a record of the network copying)
> [CA-180293] Fix network setting copying on windows 2k8

- src/xenguestlib/AutoUpdate.cs
> CA-184949: Add URL redirect support

- src/xenguestlib/Snapshot.cs
Adds an enum to describe known errors, so that the name can be displayed
as control/snapshot/error/message (in addition to control/snapshot/error/code)
> Write friendly message along with error code when VSS fails

- proj/xenupdater/xenupdater.csproj
- src/xenupdater/XenUpdater.Exe.Config
> Add XenUpdater.Exe.Config

- src/xenupdater/Program.cs
> Catch and report some specific exceptions

- src/xenupdater/Tasks.cs
> Update task's account to SID of LocalSystem

- src/xendeprivclient/XenDpriv.Exe.Config
- src/xenguestagent/XenGuestAgent.Exe.Config
Make config files compatible with .NET versions >= 3.5
> CA-196843: Always copy .exe.config files to install dir

- src/xenguestlib/AutoUpdate.cs
> CA-196881: 'xenupdater.exe' -> 'ManagementAgentUpdater.exe'

- src/xenupdater/AutoUpdate.cs
* Change default install path
<Program Files>\Citrix\XenTools or value in registry Install_Dir
* Fix update version checks
x.y.z.b == x.y.z.b is not downloaded
* Fix minimum version supported
6.6.0.0 or above required, no logging on disallowed versions
* If branding default URL fails, use hardcoded default value
throw an exception if overridden to null/empty
> Various minor fixes

- src/xenupdater/AutoUpdate.cs
If /guest_agent_features/Guest_agent_auto_update/parameters/enabled is
present, use the value to determine updates allowed/disallowed
If /guest_agent_features/Guest_agent_auto_update/parameters/enabled is
absent, use XD's presence/absence to determine updates disallowed/allowed
> Enable updates by default unless XD is present

- src/xenupdater/AutoUpdate.cs
- src/xenupdater/Wmi.cs
Correct typo if connecting to a session that already exists
> Add logging when download fails

- proj/xenguestlib/xenguestlib.csproj
- src/xenguestagent/XenService.cs
- src/xenguestlib/FeatureStaticIpSetting.cs
- src/xenguestlib/NetInfo.cs
- src/xenguestlib/Wmi.cs
change the code according to comments on https://github.com/xenserver/win-xenguestagent/pull/54
upload a new pull request
Signed-off-by: Chunjie Zhu <chunjie.zhu@citrix.com>
> CP-15241: win-guestagent set static ip set according to xenstore key

- src/xenupdater/AutoUpdate.cs
- src/xenupdater/Wmi.cs
Creating a ManagementObject directly uses an infinite timeout
Also fixes several "minor" issues
> [CA-199207] Fix download entitlement detection

- src/xenguestlib/FeatureStaticIpSetting.cs
> CA-204222: Add exception handling for remove all network in VM

- src/xenguestlib/FeatureStaticIpSetting.cs
> CA-204238: Use unit to translate the return error of IP set

- src/xenguestlib/FeatureStaticIpSetting.cs
> CA-205586: Avoid unset IP when ipenable been set with empty value

- src/xenguestagent/XenService.cs
Reverts xenserver/win-xenguestagent#65
> Revert "CA-205586 : Turn off FeatureStaticIpSetting"

- src/xenguestagent/XenService.cs
Reverts xenserver/win-xenguestagent#67
Turn off static ip setting feature
> Revert "Revert "CA-205586 : Turn off FeatureStaticIpSetting""

- src/xenguestlib/FeatureStaticIpSetting.cs
> CA-205586: Reserve orginal IP settings before set IP by agent

- src/xenguestagent/XenService.cs
Reverts xenserver/win-xenguestagent#68
So that's Turn On FeatureStaticIpSetting
> Revert "Revert "Revert "CA-205586 : Turn off FeatureStaticIpSetting"""

- src/xenguestlib/FeatureStaticIpSetting.cs
> CA-207769: Fix bug of IPv6 cannot set to none

- src/xenguestlib/FeatureStaticIpSetting.cs
> CA-204238: Set gateway again if add gateway failed

- src/xenupdater/AutoUpdate.cs
- src/xenupdater/Program.cs
CA-209312 - Log failures to download updates.tsv
CA-209253 - Only allow a single instance of ManagementAgentUpdater to run at any time
> Log updates.tsv failures and only allow a single instance

- proj/xenguestlib/XenAppSessionInfo.cs
- proj/xenguestlib/xenguestlib.csproj
- src/xenguestagent/XenService.cs
This code change is to make guest agent to have the ability to report XenApp Session count.
> CP-16911: Query for XenApp active session

- src/xenguestlib/PVInstallation.cs
> CA-212899: Add refresh when license status changed

- src/xenupdater/Program.cs
> Use a named mutex to ensure only a single instance is run

- src/branding/branding.py
- src/xenupdater/AutoUpdate.cs
Default to branding settings when no registry entry is present
> Take note of xenstore when installing updates

- src/IXenConsoleComm/IXenConsoleComm.cs
- src/XenConsoleComm/XenConsoleStream.cs
> Implement the Dispose pattern for 'XenConsoleStream'

- src/XenConsoleComm/XenConsoleStream.cs
The race condition manifests when 'XenConsoleStream.Dispose()' is
called. This internally calls 'NamedPipeClientStream.Dispose()', which
makes 'BeginRead()' complete with 0 bytes read, and then sets
'_xenConsoleClient' to 'null'.
Now since 'BeginRead()' completed, 'OnXenConsoleMessageReceived()'
fires. By the time the code reaches the 'if you read 0 bytes, dispose'
part, '_xenConsoleClient' might already be 'null', which throws an
Exception.
> Fix race condition when disposing 'XenConsoleStream' object

- src/xenguestagent/XenService.cs
- src/xenguestlib/NetInfo.cs
Signed-off-by: Lin Liu <lin.liu@citrix.com>
> CP-26040: Collect guest metric into xenstore

- proj/xenguestlib/Util.cs
- proj/xenguestlib/xenguestlib.csproj
- src/xenguestlib/NetInfo.cs
Signed-off-by: Lin Liu <lin.liu@citrix.com>
> CP-26265: Report SRIOV nic info even soft-mac changed

- proj/xenguestlib/Util.cs
- src/UnitTester/UTHelper.cs
- src/UnitTester/UnitTester.csproj
- src/UnitTester/UtilTester.cs
- src/UnitTester/VifInfoTester.cs
- src/xenguestagent/XenService.cs
- src/xenguestlib/FeatureStaticIpSetting.cs
- src/xenguestlib/NetInfo.cs
Signed-off-by: Lin Liu <lin.liu@citrix.com>
- Enable `staticIpSetting` for sriov VF
- Enable  `staticIpSetting` feature support change soft-mc inside VM
> CP-25612: Enable static ip setting for VFs
